== Record Parser

The record parser allows you to easily parse protocols which are delimited by a sequence of bytes, or fixed
size records.

It transforms a sequence of input buffer to a sequence of buffer structured as configured (either
fixed size or separated records).

For example, if you have a simple ASCII text protocol delimited by '\n' and the input is the following:

[source]
----
buffer1:HELLO\nHOW ARE Y
buffer2:OU?\nI AM
buffer3: DOING OK
buffer4:\n
----

The record parser would produce
[source]
----
buffer1:HELLO
buffer2:HOW ARE YOU?
buffer3:I AM DOING OK
----

Let's see the associated code:

[source, java]
----
final RecordParser parser = RecordParser.newDelimited("\n", h -> {
  System.out.println(h.toString());
});

parser.handle(Buffer.buffer("HELLO\nHOW ARE Y"));
parser.handle(Buffer.buffer("OU?\nI AM"));
parser.handle(Buffer.buffer("DOING OK"));
parser.handle(Buffer.buffer("\n"));
----

You can also produce fixed sized chunks as follows:

[source, java]
----
RecordParser.newFixed(4, h -> {
  System.out.println(h.toString());
});
----

For more details, check out the `link:../../apidocs/io/vertx/core/parsetools/RecordParser.html[RecordParser]` class.

== Json Parser

You can easily parse JSON structures but that requires to provide the JSON string at once, but it
may not be convenient when you need to parse very large structures.

The non-blocking JSON parser is an event driven parser able to deal with very large structures.
It transforms a sequence of input buffer to a sequence of JSON parse events.

[source, java]
----
JsonParser parser = JsonParser.newParser();

// Set handlers for various events
parser.startArrayHandler(v -> {
  // Start an array
});
parser.endArrayHandler(v -> {
  // End an array
});
parser.startObjectHandler(json -> {
  // Start an objet
});
parser.endObjectHandler(json -> {
  // End an objet
});

parser.valueHandler(value -> {
  // Handle a field
  String field = parser.currentField();
  if (field != null) {
    // In an object
  } else {
    // In an array or top level
  }
});
----

The parser is non-blocking and emitted events are driven by the input buffers

[source, java]
----
JsonParser parser = JsonParser.newParser();

// start array event
// start object event
// "firstName":"Bob" event
parser.handle(Buffer.buffer("[{\"firstName\":\"Bob\"},"));

// "lastName":"Morane" event
// end object event
parser.handle(Buffer.buffer("\"lastName\":\"Morane\")},"));

// start object event
// "firstName":"Luke" event
// "lastName":"Lucky" event
// end object event
parser.handle(Buffer.buffer("{\"firstName\":\"Luke\",\"lastName\":\"Lucky\")}"));

// end array event
parser.handle(Buffer.buffer("]"));

// Always call end
parser.end();
----

Event driven parsing provides more control but comes at the price of flexibility. The parser allows you
to handle JSON structures when it is desired:

[source, java]
----
JsonParser parser = JsonParser.newParser();

parser.startArrayHandler(v -> {
  // Start the array
});
parser.endArrayHandler(v -> {
  // End the array
});
parser.objectHandler(json -> {
  // Handle each object
});

parser.handle(Buffer.buffer("[{\"firstName\":\"Bob\"},\"lastName\":\"Morane\"),...]"));
parser.end();
----

The object and array handlers can be set and unset during the parsing allowing you to switch between fine grained
events or JSON object/array events.

[source, java]
----
JsonParser parser = JsonParser.newParser();

parser.startObjectHandler(v -> {
  // Start the object

  // Set an object handler to handle each entry, from now on the parser won't emit start object events
  parser.objectHandler(json -> {
    // Handle each object
    // Get the field in which this object was parsed
    String id = parser.currentField();
    System.out.println("User with id " + id + " : " + json.encodePrettily());
  });
});
parser.endObjectHandler(v -> {
  // Clear the object handler so the parser emits start/end object events again
  parser.objectHandler(null);
});

parser.handle(Buffer.buffer("{\"39877483847\":{\"firstName\":\"Bob\"},\"lastName\":\"Morane\"),...}"));
parser.end();
----

You can also decode POJOs

[source, java]
----
parser.objectHandler(User.class, user -> {
  // Handle each object
  // Get the field in which this object was parsed
  String id = parser.currentField();
  System.out.println("User with id " + id + " : " + user.firstName + " " + user.lastName);
});
----

Whenever the parser fails to process a buffer, an exception will be thrown unless you set an exception handler:

[source, java]
----
parser.objectHandler(User.class, user -> {
  // Handle each object
  // Get the field in which this object was parsed
  String id = parser.currentField();
  System.out.println("User with id " + id + " : " + user.firstName + " " + user.lastName);
});
----

For more details, check out the `link:../../apidocs/io/vertx/core/parsetools/JsonParser.html[JsonParser]` class.